# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ElisaApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'Logboard', '~> 2.3.1'
#    pod 'HaishinKit', :git => 'https://github.com/shogo4405/HaishinKit.swift'
  # Pods for ElisaApp

end
