# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ElisaApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'HaishinKit', '~> 1.4.5'
  # Pods for ElisaApp

end
